name: Verify and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: "Static analyze and Logic tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting and analyze project source
        run: mise run verify

      - name: Run logic tests
        run: mise run test:logic

  presentation-test:
    name: "Presentation tests"
    # Should run on same os with golden files
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Run presentation tests
        run: mise run test:presentation
